version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config:/etc/prometheus
      - ./data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
